export interface ConversationMessage {
	id: number;
	accountId: number;
	userId: number | null;
	listingMapId: number;
	reservationId: number;
	channelId: number;
	conversationId: number;
	communicationId: string | null;
	whatsappTemplateId: string | null;
	airbnbThreadMessageId: string | null;
	channelThreadMessageId: string;
	ccEmail1: string | null;
	ccEmail2: string | null;
	subject: string;
	body: string;
	imagesUrls: string | null;
	bookingcomSubthreadId: string;
	isIncoming: number;
	isSeen: number;
	isSeenBy: string | null;
	originatedBy: string;
	isSeenAt: string;
	sentUsingHostaway: number;
	hash: string;
	objectKey: string | null;
	listingTimeZoneName: string;
	communicationEvent: string | null;
	communicationTimeDelta: string | null;
	communicationTimeDeltaSeconds: number;
	communicationApplyListingTimeZone: string | null;
	communicationAlwaysTrigger: string | null;
	status: string;
	date: string;
	sentToChannelDate: string;
	sentToChannelAttemptDate: string;
	messageSource: string;
	communicationType: string;
	reasonFailed: string | null;
	readableReasonFailed: string | null;
	isUnique: string | null;
	isUniquePerCommunication: number;
	retryCount: number;
	insertedOn: string;
	updatedOn: string;
	notUpdateOnReservationChange: string | null;
	Reservation: object | null;
	ListingMap: object | null;
	Conversation: object | null;
	AirbnbOfficialMessageMetadata: object | null;
	communicationName: string | null;
	attachments: object | null;
	twilioMessageIdConversationMessageId: string | null;
	attachment: object | null;
	conversationMessageNote: any[];
	conversationSnooze: any[];
	conversationArchive: any[];
}

export interface Reservation {
	id: number;
	listingMapId: number;
	listingName: string;
	channelId: number;
	source: string;
	channelName: string;
	reservationId: string;
	hostawayReservationId: string;
	channelReservationId: string;
	externalPropertyId: string;
	externalUnitId: string;
	assigneeUserId: number | null;
	customerIcalId: string | null;
	customerIcalName: string | null;
	guestAuthHash: string | null;
	guestPortalUrl: string | null;
	guestPortalRevampUrl: string | null;
	isProcessed: number;
	isInitial: number;
	isManuallyChecked: number;
	isInstantBooked: number;
	reservationDate: string;
	pendingExpireDate: string | null;
	guestName: string;
	guestFirstName: string;
	guestLastName: string;
	guestExternalAccountId: string | null;
	guestZipCode: string | null;
	guestAddress: string | null;
	guestCity: string;
	guestCountry: string;
	guestEmail: string;
	guestPicture: string | null;
	guestRecommendations: number;
	guestTrips: number;
	guestWork: string | null;
	isGuestIdentityVerified: number;
	isGuestVerifiedByEmail: number;
	isGuestVerifiedByWorkEmail: number;
	isGuestVerifiedByFacebook: number;
	originalChannel: string | null;
	isGuestVerifiedByGovernmentId: number;
	isGuestVerifiedByPhone: number;
	isGuestVerifiedByReviews: number;
	numberOfGuests: number;
	adults: number;
	children: number | null;
	infants: number | null;
	pets: number | null;
	arrivalDate: string;
	departureDate: string;
	isDatesUnspecified: number;
	previousArrivalDate: string | null;
	previousDepartureDate: string | null;
	checkInTime: number;
	checkOutTime: number;
	nights: number;
	phone: string;
	totalPrice: number;
	remainingBalance: number | null;
	taxAmount: number | null;
	channelCommissionAmount: number;
	hostawayCommissionAmount: number | null;
	cleaningFee: number;
	securityDepositFee: number | null;
	isPaid: number | null;
	ccName: string | null;
	ccNumber: string | null;
	ccNumberEndingDigits: string | null;
	ccExpirationYear: string | null;
	ccExpirationMonth: string | null;
	cvc: string | null;
	stripeGuestId: string | null;
	stripeMessage: string | null;
	braintreeGuestId: string | null;
	braintreeMessage: string | null;
	currency: string;
	status: string;
	paymentStatus: string;
	cancellationDate: string | null;
	cancelledBy: string | null;
	hostNote: string | null;
	guestNote: string;
	doorCode: string | null;
	doorCodeVendor: string | null;
	doorCodeInstruction: string | null;
	comment: string;
	confirmationCode: string | null;
	airbnbExpectedPayoutAmount: number | null;
	airbnbListingBasePrice: number | null;
	airbnbListingCancellationHostFee: number | null;
	airbnbListingCancellationPayout: number | null;
	airbnbListingCleaningFee: number | null;
	airbnbListingHostFee: number | null;
	airbnbListingSecurityPrice: number | null;
	airbnbOccupancyTaxAmountPaidToHost: number | null;
	airbnbTotalPaidAmount: number | null;
	airbnbTransientOccupancyTaxPaidAmount: number | null;
	airbnbCancellationPolicy: string | null;
	isStarred: number;
	isArchived: number;
	isPinned: number;
	reservationCouponId: string | null;
	customFieldValues: any[];
	reservationFees: any[];
	reservationUnit: any[];
	insertedOn: string;
	updatedOn: string;
	latestActivityOn: string | null;
	customerUserId: string | null;
	guestLocale: string | null;
	localeForMessaging: string | null;
	localeForMessagingSource: string | null;
	listingCustomFields: object | null;
	rentalAgreementFileUrl: string | null;
	reservationAgreement: string;
	financeField: any[];
	guestPaymentCardIsVirtual: string | null;
	insuranceStatus: string | null;
	claimStatus: string | null;
	insurancePolicyId: string | null;
	cancellationPolicyId: string | null;
	hostProxyEmail: string | null;
}

export interface Conversation {
	id: number;
	accountId: number;
	listingMapId: number;
	reservationId: number;
	type: string;
	recipientEmail: string;
	recipientName: string;
	recipientPicture: string | null;
	hostEmail: string;
	guestEmail: string;
	hasUnreadMessages: number;
	messageSentOn: string;
	messageReceivedOn: string;
	conversationMessages: ConversationMessage[];
	Reservation: Reservation;
}
